// <auto-generated />
namespace AqApplication.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class pdf2modfication : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pdf2modfication));
        
        string IMigrationMetadata.Id
        {
            get { return "201806101104589_pdf2modfication"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
